### PR TITLE
remove unused dependencies

### PR DESCRIPTION
**Pull request by brad-decker**
went to upgrade ethereumjs-util and then realized its not being used. Also eth-query was a similar way so i removed both.

### CODE REVIEW

**Review by ryanml — COMMENTED** [review]
looks good as i think these are still both sub-deps of other dependencies, but just wanted to double check to make sure there were no needed modifications to `yarn.lock`

**Comment by brad-decker** [comment]
i swore i ran yarn remove. Thanks for pointing this out @ryanml !

**Comment by brad-decker** [comment]
weird, well did the process again and it still doesn't result in a lockfile change

**Review by ryanml — APPROVED** [review]
Hm, the change could very well just not be needed. Thanks for double checking on it!

**Comment by Gudahtt** [comment]
If another dependency asks for precisely the same range of each of these packages, I'd expect there to be no changes. Not especially common, but I guess that's what happened here!

**Pull request merged**
