### PR TITLE
fix(wallet): add back missing txData for signTransaction,sendTransaction

### LINKED ISSUE #262: `txParams`  getting overwritten in wallet middleware
Recently it was discovered that when upgrading the extension to `eth-json-rpc-middleware` 12.0.0, after sending a transaction via the test dapp, the following error shows up in the console for the background:

> Invalid transaction params: must specify "data" for contract deployments, or "to" (and optionally "data") for all other types of transactions.

It turns out that [this commit](https://github.com/MetaMask/eth-json-rpc-middleware/commit/3910dad7b5411ba2d4cf89bc6eb6f9358f04fd6d#diff-5eaa3c61f9e2360b928d6ec7872297c8f9c7c3ba83724ddb9ee9eb937c954308R158) introduced unintentional breaking changes. In `wallet.ts` -> `sendTransaction`, the `txParams` object is getting completely blown away and replaced with an object that has a single `from` property. This breaks the existing functionality around sending transactions. Other functions have similar issues. We should fix `wallet.ts` so that this does not occur.

Oddly, this didn't break any tests. So, we should make sure to add those as well so that this is not an issue going forward.

### PR DESCRIPTION
**Pull request by legobeat**
- Resolves #262 

- [x] Add regression test(s)
  - Should fail on `main` but pass on top of this PR

### CODE REVIEW

**Review by mcmire — COMMENTED** [review]
Thank you for doing this. I have looked through your previous commit and compared it to this PR, and it looks like these are the only two that needed to changed.

**Comment by mcmire** [comment]
@legobeat Anything I can do to help you with this? I want to unblock the extension team so that they can upgrade this in the extension, so I'm happy to help you add the missing tests.

**Comment by cryptodev-2s** [comment]
@mcmire I will work on the tests Tomorrow

**Comment by cryptodev-2s** [comment]
replaced by https://github.com/MetaMask/eth-json-rpc-middleware/pull/266

**Review by mcmire — APPROVED** [review]
Looks great, thank you!

**Pull request merged**
