### PR TITLE
Apply standardizations from module template

### PR DESCRIPTION
**Pull request by mcmire**
* Upgrade to Yarn 3.x
* Move test files into `src/` instead of keeping them in `test/`
* Convert Jest config file back to JavaScript
* Add `eslint-plugin-jest` to lint pipeline, and correct issues
* Extract build-only config from `tsconfig.json`
* Standardize `package.json`
  * Don't add `jest-it-up` to the `test` command because there is
    currently an inconsistency between different Node versions (14.x and
    16.x) which may have to do with global `fetch`
* Upgrade `@metamask/allow-scripts` to 2.x
* Upgrade `@metamask/utils` to ^3.0.3

### CODE REVIEW

**Comment by mcmire** [comment]
Need to bump this library to Node 16 to prevent from having to resolve `superstruct` to 0.16.0. Because `metamask-mobile` uses this library, though, I'm placing this in draft until that repo can be bumped to Node 16 to avoid any surprises.

**Comment by mcmire** [comment]
Working to get `superstruct` fixed so that it doesn't need Node 16.

**Comment by mcmire** [comment]
@socket-security ignore bufferutil@4.0.6
@socket-security ignore keccak@3.0.2
@socket-security ignore secp256k1@4.0.3
@socket-security ignore utf-8-validate@5.0.9
@socket-security ignore @swc/core@1.3.3

**Comment by mcmire** [comment]
@SocketSecurity ignore bufferutil@4.0.6
@SocketSecurity ignore keccak@3.0.2
@SocketSecurity ignore secp256k1@4.0.3
@SocketSecurity ignore utf-8-validate@5.0.9
@SocketSecurity ignore @swc/core@1.3.3

**Review by Gudahtt — DISMISSED** [review]
LGTM!

**Comment by mcmire** [comment]
Merged updates from `main` and fixed lint issues.

**Review by Gudahtt — APPROVED** [review]

**Pull request merged**
